apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-pvc
  namespace: tools                   
  labels:
    app: ProjectDevops-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi 